### ISSUE TITLE
JSON string maxlength does not support UTF-8

### ISSUE THREAD

**Issue by zufler** [gregsdennis/Manatee.Json#217]
if the string is unicoded with UTF-8 maxlength is validated incorrectly due to difference in encoding Hint :- use encoding.utf8.getbytecount(string) to validate length instead string.length 
Thank you

**Comment by gregsdennis** [comment]
Thanks for the report.  I'd like to set up a test for this.  Could you suggest a couple examples that don't work with the current version, please?

**Comment by zufler** [comment]
try to validate maxlength for this :=  "data": "“Silly Gooseberry!”"
You can see qoutation (“) is different than ascii char (")

**Comment by gregsdennis** [comment]
I added a test to the schema tests:

```c#
[Test]
public void Issue217_MaxLengthDoesNotSupportUtf8Properly()
{
	var json = new JsonObject {["data"] = "“Silly Gooseberry!”"};
	var schema = new JsonSchema()
		.Type(JsonSchemaType.Object)
		.Property("data", new JsonSchema()
			          .MaxLength(20));

	var results = schema.Validate(json);

	results.AssertValid();
}
```

It passes.

**Comment by zufler** [comment]
But its unicoded string whose actual length is 23

**Comment by zufler** [comment]
as 1 char has 1 byte try using encoding.utf8.getbytecount(string) to check byte count you will get 23

**Comment by zufler** [comment]
and if you use simple ascii encoding it return 20

**Comment by zufler** [comment]
so it should have returned false for maxlength 20 as its utf8 byte count is 23

**Comment by gregsdennis** [comment]
From [JSON Schema draft 7, section 6.3.1](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.3.1)

> The length of a string instance is defined as the number of its characters as defined by RFC 7159 [RFC7159].

Moving on to [RFC7159, section 8](https://tools.ietf.org/html/rfc7159#section-8) we see that the "length" of a string is not well-defined.

We've had discussions on the JSON Schema specification GH or Slack around this, and we count _characters_ not bytes.  (I actually had to update my implementation as a result of this conversation because I was using `string.Length` which, as you pointed out, is wrong.)
