### ISSUE TITLE
Support for unity3d IL2CPP?

### ISSUE THREAD

**Issue by damon-kwok** [gregsdennis/Manatee.Json#32]
Support for unity3d IL2CPP?

**Comment by gregsdennis** [comment]
I don't understand your request.  It appears that IL2CPP is a universal tool that converts IL to something useful to Unity.  It should just work.

**Comment by gregsdennis** [comment]
@damon-kwok, can you expand on your request, please?

**Comment by gregsdennis** [comment]
@damon-kwok, I'm going to close this for now, pending further information from you.

**Comment by SugoiDev** [comment]
Necroing this issue to add a bit of information for future travelers.

The major issue with Unity is that a lot of its supported platforms are AOT only.
Without JIT, we can't emit or compile any code dynamically, and all generic types must be known at compile time.

Since this library emits IL, it won't work on AOT-only platforms, like iOS and game consoles.
